### ISSUE TITLE
New Value field is causing problems with people that don't understand what is happening

### ISSUE THREAD

**Issue by jgoggan** [HaJaeKyung/KittyExtension#15]
Unfortunately, the new Value indicator is a poor indicate of real value.  It's good for a quick check of average stuff, but not great for rare cattributes because it doesn't have enough data.

Consider this: https://i.imgur.com/sbQP5dr.png

The two Fabulous cats on the left and right should be worth about the same (and that value is probably around 0.2ETH or so!), but it shows them as wildly different.  The problem is that the plugin is searching for "Fabulous emeraldgreen" and finding very few of those -- so it uses that 2.65 value.  The one on the right is searching for "fabulous whixtensions" and finds a few more and gets a lower average even though it likely should be worth more than the one on the left -- since it has two rare traits.

I think it needs to better warn people or something.  Or, maybe if it finds less than some threshold level of matches, that it says it can't determine the value.  So that you need at least X that match and X should be probably at least 20 or something.

I also think it should ignore cattributes from a different level.  Right now, it takes the top two, right?  But I feel like if there is only one red-level rare, then it should just use that -- because whatever the next down yellow "uncommon" probably doesn't matter.  You'd get better data that way.

Because, really, for the one on the left in the example, it should be an average of just fabulous cats since the emeraldgreen doesn't mean much.  In which case, the value is more like 0.2ETH instead of 2.65ETH.  It just doesn't have enough data when it picks the 2.65ETH.

Just a thought -- because newbies on the Discord are so very confused about value because of this extension.  :(

Thanks!

**Comment by VesterDe** [comment]
I agree, I've seen people say thing based on this value attribute that are far from making sense...

Maybe shelve the feature until something more powerful can be constructed?

**Comment by HaJaeKyung** [comment]
I agree mostly but think it is too late to remove and would rather just improve it. I meant it to be more of a general guide when listing your kitties and to click on the value to bring up the search to give a better idea. I think in general it works well but some fringe cases with rare attributes throw it off. Multiple refinement requests would improve the results but think more than one request would kill the servers at the moment.

**Comment by jgoggan** [comment]
Yeah, I don't think you can undo it now.  But it just needs to be better.

I don't think it "generally works well."  Seriously -- go into the Discord for a while and you'll see all kinds of newbies trying to use that value to do things and it doesn't make any sense.  It's simply wrong.  It's only good for average cats.  Put anything rare in there and it gets crazy because it picks TWO cattributes even if one is significantly less rare.  That's why It think if the rarity is a big gap (like a red to a yellow), then it should ONLY search for the red.  That sort of thing.

So, I'd still recommend that it just be adjusted to only use TWO cattributes if they are the same level.  If they are different levels, then just use the more rare cattribute in the search.  I think that would help a great deal.

**Comment by HaJaeKyung** [comment]
Just pushed a new update and it should be much better now. It also now factors in cooldown and resting.

**Comment by jgoggan** [comment]
So, it looks like you've adjusted how it uses the cattributes too?  It did better with the situation where one had fabulous, for example, since it only does that one now in the search.  But then I have another that is a Gen 9 with cymric (which isn't anything too special).  Are you still including cymric in the search?  Or just the gen:9?  Because it appears to just do gen:9.  Just curious.

Also, not sure if you can do anything about this, but it is wrong for Vampires.  There isn't a way to identify them that I know of.  So you're just comparing them to any fancy, right?  So it lists a really low value (0.1 ETH) when I think the cheapest Vampire right now is 3ETH and the next 3 are 10ETH each.

But, again, maybe nothing can be done there because I don't know if you can detect things like Vampires.
