### ISSUE TITLE
Empty data for some kitties

### ISSUE THREAD

**Issue by mikelortega** [HaJaeKyung/KittyExtension#19]
It seems quite random, it fails with sometimes, but not always. I haven't found a reason or a general rule to make it fail.
In the value box it says: value: Name your price
In the traits: [object Object]

![image](https://user-images.githubusercontent.com/3043173/33687053-1f62c5c2-dad7-11e7-8cf5-d663e6f0d127.png)

**Comment by HaJaeKyung** [comment]
The devs updated the site with new info. Working on fixing.

**Comment by mikelortega** [comment]
Yes, I've just updated and it works :)
Now I cannot see the value, but that would be another issue.
Thank you 🙀
