### ISSUE TITLE
Version 23 all has name your price

### ISSUE THREAD

**Issue by webworker01** [HaJaeKyung/KittyExtension#20]
![image](https://user-images.githubusercontent.com/3256000/33687863-875cf8c6-daa7-11e7-9cea-dc6ee2b6fc9f.png)

**Comment by HaJaeKyung** [comment]
The developers changed the site, going to take a little bit to rewrite the code.

**Comment by HaJaeKyung** [comment]
Should be all fixed now 0.27

**Comment by webworker01** [comment]
Yes, you are a friend to all kitteh, ty!
