### ISSUE TITLE
Chrome No Longer Works - shows {Object Object]

### ISSUE THREAD

**Issue by mhannigan** [HaJaeKyung/KittyExtension#21]
There are no cattributes listed.  Where each would be, only [Object Object] is shown.

**Comment by Professor333** [comment]
You may be using an older version of the script code. Just copy and paste the current script on github into Tampermonkey to make sure you are up to date.

**Comment by SydnaA** [comment]
It no longer works for me on chrome.

```
Uncaught TypeError: Cannot read property 'innerText' of undefined
    at HTMLAnchorElement.overlay (eval at <anonymous> (:2:479), <anonymous>:152:75)
    at HTMLBodyElement.dispatch (eval at <anonymous> (:2:479), <anonymous>:6:10316)
    at HTMLBodyElement.q.handle (eval at <anonymous> (:2:479), <anonymous>:6:8343)
```

<img width="645" alt="screen shot 2017-12-06 at 8 57 19 pm" src="https://user-images.githubusercontent.com/8703653/33694877-84246ef2-dac8-11e7-8eff-342f9779af2f.png">

Not sure if same issue as yours.

**Comment by Hog-Fillet** [comment]
Same issue here, just upgraded from 0.20

**Comment by jgoggan** [comment]
The Object Object thing usually means you're on an older version.

That being said, 0.27 is not working right now either -- just shows nothing for me and anyone else I've asked in the Discord.

**Comment by henrylai** [comment]
Change L144, and L146 from using:
children[0].children[1].children[2].innerText
to
children[0].children[1].children[1].innerText

**Comment by henrylai** [comment]
Submitted a pull request for the fix. Alternatively you can use the forked repo with the fix:
https://github.com/henrylai/KittyExtension/blob/master/script

**Comment by jgoggan** [comment]
Actually, on line 148, you need children[0] for the last one, right?  It's already children[1].

**Comment by henrylai** [comment]
No changes needed for L148, my mistake, edited comment above.
