### ISSUE TITLE
Color on Mac Chrome are not the same as PC Chrome

### ISSUE THREAD

**Issue by mankinchi** [HaJaeKyung/KittyExtension#23]
I got different color when I check my Mac against my Window. Is this intended?

![screen shot 2017-12-07 at 3 01 00 pm](https://user-images.githubusercontent.com/8164063/33698265-82e3c0f0-db5f-11e7-8140-716aee323bb9.png)

**Comment by HaJaeKyung** [comment]
The colors were changed. You are probably using different versions?

**Comment by mankinchi** [comment]
I'm using 0.28, I believe

**Comment by jungwoolee98** [comment]
The screenshot you attached is the intended color scheme according to v 0.28
