### ISSUE TITLE
value estimator using kitten name as gen

### ISSUE THREAD

**Issue by SebRut** [HaJaeKyung/KittyExtension#25]
Script Version: 0.28
Browser: Google Chrome 62.x
Problem: The script extracts the kitten's name as gen

At the moment For example clicking on the value of this [cat](https://www.cryptokitties.co/kitty/69472) leads to this search [query](https://www.cryptokitties.co/marketplace/sale?type=sale&limit=15&sorting=cheap&orderBy=current_price&orderDirection=asc&sorting=cheap&status=open&search=%20gen:Emerald%20Cymric%20mauve%20%20emeraldgreen%20mauveover): "gen:Emerald Cymric mauve  emeraldgreen mauveover"

**Comment by HaJaeKyung** [comment]
Should be fixed
