### ISSUE TITLE
Pricing is inaccurate and slows the load time for every page

### ISSUE THREAD

**Issue by nhayfield** [HaJaeKyung/KittyExtension#33]
The pricing is not close to accurate and also really slows the site down. 
I have removed it here:
https://github.com/nhayfield/KittyExtension

I also added a show/hide type functionality. 
I will be adding a new search function which should be optimized for speed in near future.

**Comment by jgoggan** [comment]
It was already removed from the latest release here like 30-45 minutes before you posted this.
