### ISSUE TITLE
CD parameter

### ISSUE THREAD

**Issue by Timoffey** [HaJaeKyung/KittyExtension#38]
[txt.txt](https://github.com/HaJaeKyung/KittyExtension/files/1544786/txt.txt)
I found that verison on the Russian group. Man did cooldown parameter. That pretty good idea. If parameter is even (\2=0) then first timer value, if odd (\2=1) then second time parameter.
E.g. slow 16 or 24h. if even then 16 else 24. Good idea, isn't it?

**Comment by HaJaeKyung** [comment]
Not sure if it is that useful. Anyone else have an opinion?

**Comment by Timoffey** [comment]
That may be useful to fast see what state of status kitty has. Maybe just write first or second state. maybe just add gen counter to number of childs and show actual timer caption.

**Comment by lexxdog** [comment]
It will be very useful. 
Im not sure if i get machanics right, but if virgin kitten can have odd CoolDown index - you cannot be sure how much children it can breed before it became next level of cooldown (swift to snappy etc)
So this feature would be just a _musthave_ during market time.

**Comment by PantsStatusZero** [comment]
The status.cooldown_index seems give you the exact time:

0 = 1m fast
1 = 2m Swift
2 = 5m Swift
3 = 10m Snappy
4 = 30m Snappy
5 = 1hr Brisk
6 = 2hr Brisk
7 = 4h Plodding
8 = 8h Plodding
9 = 16h Slow
10 = 24h Slow
11 = 2d Sluggish
12 = 4d Sluggish
13 = 1 week Catatonic
