### ISSUE TITLE
It won't work now

### ISSUE THREAD

**Issue by normanx** [HaJaeKyung/KittyExtension#47]
I have just open my account, but when mouse point hover on a cat in list, the cattributes hasn't show as before. I use Chrome 63.0.3239.84 (Official Build) (64-bit) under MacOSX.

Please check this issue, Thank you very much!

**Comment by MarieEsp** [comment]
I think it is b/c they just added the "like" feature.
Mine stopped working at about the time that feature came online.

**Comment by MarieEsp** [comment]
Thank you for fixing it! 
I am going to send a donation to your account. Not as much as you deserve, but hopefully others are sending you donations as well!

**Comment by MarieEsp** [comment]
I don't know how to direct message you, but I do hope you got my donation (and that I didn't send it to the wrong person)!

**Comment by HaJaeKyung** [comment]
@MarieEsp Thanks so much. Really appreciate it! 😍
